gateway:
  port: 8084
  data-path: data
  temp-path: temp

logger:
  output: both
  level: info
  log-path: logs/server.log
  request-log-path: logs/request.log
  max-size: 64
  max-backups: 7
  max-age: 30
  compress: false

oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  access-key-id: YOUR_ACCESS_KEY_ID
  access-key-secret: YOUR_ACCESS_KEY_SECRET
  bucket-name: your-bucket
  url-expire-seconds: 3600
