/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdjustControls: typeof import('./src/components/settings/AdjustControls.vue')['default']
    ChatView: typeof import('./src/components/ChatView.vue')['default']
    HomePanel: typeof import('./src/components/home/HomePanel.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    LanguageSelect: typeof import('./src/components/firstRun/LanguageSelect.vue')['default']
    Live2dBehaviorControls: typeof import('./src/components/settings/Live2dBehaviorControls.vue')['default']
    LlmConnect: typeof import('./src/components/firstRun/LlmConnect.vue')['default']
    ModelManagement: typeof import('./src/components/settings/ModelManagement.vue')['default']
    ModelSelect: typeof import('./src/components/firstRun/ModelSelect.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSwitch: typeof import('naive-ui')['NSwitch']
    Ready: typeof import('./src/components/firstRun/Ready.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    Welcome: typeof import('./src/components/firstRun/Welcome.vue')['default']
  }
}
