/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSettings: typeof import('./src/components/settings/AboutSettings.vue')['default']
    AdjustControls: typeof import('./src/components/settings/AdjustControls.vue')['default']
    AiSettings: typeof import('./src/components/settings/AiSettings.vue')['default']
    AppButton: typeof import('./src/components/ui/AppButton.vue')['default']
    AppCard: typeof import('./src/components/ui/AppCard.vue')['default']
    AppChip: typeof import('./src/components/ui/AppChip.vue')['default']
    AppEmpty: typeof import('./src/components/ui/AppEmpty.vue')['default']
    AppField: typeof import('./src/components/ui/AppField.vue')['default']
    AppSectionHeader: typeof import('./src/components/ui/AppSectionHeader.vue')['default']
    AppSkeleton: typeof import('./src/components/ui/AppSkeleton.vue')['default']
    AppSwitchRow: typeof import('./src/components/ui/AppSwitchRow.vue')['default']
    ChatView: typeof import('./src/components/ChatView.vue')['default']
    DebugSettings: typeof import('./src/components/settings/DebugSettings.vue')['default']
    FeedbackHost: typeof import('./src/components/ui/FeedbackHost.vue')['default']
    GeneralSettings: typeof import('./src/components/settings/GeneralSettings.vue')['default']
    HomePanel: typeof import('./src/components/home/HomePanel.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    InteractionControls: typeof import('./src/components/settings/InteractionControls.vue')['default']
    InteractionRegionOverlay: typeof import('./src/components/settings/InteractionRegionOverlay.vue')['default']
    LanguageSelect: typeof import('./src/components/firstRun/LanguageSelect.vue')['default']
    Live2dBehaviorControls: typeof import('./src/components/settings/Live2dBehaviorControls.vue')['default']
    McpSettings: typeof import('./src/components/settings/McpSettings.vue')['default']
    MemorySettings: typeof import('./src/components/settings/MemorySettings.vue')['default']
    ModelManagement: typeof import('./src/components/settings/ModelManagement.vue')['default']
    ModelSelect: typeof import('./src/components/firstRun/ModelSelect.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSwitch: typeof import('naive-ui')['NSwitch']
    ProactiveSettings: typeof import('./src/components/settings/ProactiveSettings.vue')['default']
    Ready: typeof import('./src/components/firstRun/Ready.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./src/components/settings/SettingsPanel.vue')['default']
    SkillsSettings: typeof import('./src/components/settings/SkillsSettings.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    VoiceSettings: typeof import('./src/components/settings/VoiceSettings.vue')['default']
    Welcome: typeof import('./src/components/firstRun/Welcome.vue')['default']
  }
}
