using Avalonia.Media;

namespace Nori.Desktop.Settings;

/// <summary>
/// 原生设置资源字典。
///
/// 设置窗口只支持 zh-CN 与 en-US；其它持久化语言值不被改写，显示时回退中文。
/// </summary>
public static class SettingsLocalization
{
	private static readonly IReadOnlyDictionary<string, (string Zh, string En)> Resources =
		new Dictionary<string, (string Zh, string En)>(StringComparer.Ordinal)
		{
			["window.title"] = ("Nori 设置", "Nori Settings"),
			["window.subtitle"] = ("管理 Nori 的 AI、语音、记忆与工具能力", "Manage Nori's AI, voice, memory and tools"),
			["common.close"] = ("关闭", "Close"),
			["common.save"] = ("保存", "Save"),
			["common.cancel"] = ("取消", "Cancel"),
			["common.confirm"] = ("确认执行", "Confirm"),
			["common.refresh"] = ("刷新", "Refresh"),
			["common.loading"] = ("处理中…", "Working…"),
			["common.error"] = ("操作失败", "Operation failed"),
			["common.none"] = ("暂无", "None"),
			["common.all"] = ("全部", "All"),
			["nav.ai"] = ("AI 大脑", "AI Brain"),
			["nav.voice"] = ("语音音效", "Voice & Audio"),
			["nav.proactive"] = ("主动日程", "Proactive & Routine"),
			["nav.memory"] = ("长期记忆", "Memory Library"),
			["nav.skills"] = ("技能工坊", "Skills Workshop"),
			["nav.mcp"] = ("工具与 MCP", "Tools & MCP"),
			["nav.general"] = ("系统常规", "General System"),
			["nav.debug"] = ("调试诊断", "Debug & Diagnostics"),
			["ai.title"] = ("AI 大脑", "AI Brain"),
			["ai.subtitle"] = ("连接 OpenAI、Anthropic、Google GenAI 或兼容接口", "Connect OpenAI, Anthropic, Google GenAI or compatible endpoints"),
			["ai.provider"] = ("协议类型", "Provider"),
			["ai.baseUrl"] = ("API 地址", "API base URL"),
			["ai.apiKey"] = ("API Key", "API Key"),
			["ai.model"] = ("模型", "Model"),
			["ai.persona"] = ("人格与系统提示词", "Persona & system prompt"),
			["ai.personaHint"] = ("留空使用默认陪伴人设。", "Leave empty to use Nori's default companion persona."),
			["ai.fetch"] = ("获取模型", "Fetch models"),
			["ai.fetching"] = ("获取中…", "Fetching…"),
			["ai.saved"] = ("已加密保存", "Saved securely"),
			["voice.title"] = ("语音与音效", "Voice & Audio"),
			["voice.subtitle"] = ("配置 TTS、STT 与全局输出音量", "Configure TTS, STT and output volume"),
			["voice.volume"] = ("全局输出音量", "Master volume"),
			["voice.provider"] = ("TTS 服务提供商", "TTS provider"),
			["voice.openai"] = ("OpenAI / 兼容接口", "OpenAI / compatible"),
			["voice.custom"] = ("自定义 HTTP 端点", "Custom HTTP endpoint"),
			["voice.gpt"] = ("GPT-SoVITS API", "GPT-SoVITS API"),
			["voice.baseUrl"] = ("TTS API 地址", "TTS API URL"),
			["voice.apiKey"] = ("TTS API Key", "TTS API Key"),
			["voice.voice"] = ("朗读音色", "Voice"),
			["voice.speed"] = ("语速", "Speed"),
			["voice.autoPlay"] = ("对话自动朗读", "Read replies automatically"),
			["voice.autoPlayDesc"] = ("生成回复后自动播放语音。", "Play generated replies automatically."),
			["voice.refAudio"] = ("参考音频路径", "Reference audio path"),
			["voice.promptText"] = ("参考音频文本", "Reference text"),
			["voice.promptLang"] = ("参考音频语言", "Reference language"),
			["voice.test"] = ("试听当前音色", "Test current voice"),
			["voice.noticeTitle"] = ("检测到旧版浏览器语音配置", "Legacy browser voice settings detected"),
			["voice.notice"] = ("纯后端版本不再支持 Web Speech / 浏览器 Edge-TTS，请改用下方的语音服务。", "The native runtime no longer supports Web Speech / browser Edge-TTS. Use one of the providers below."),
			["voice.dismiss"] = ("知道了", "Dismiss"),
			["voice.stt"] = ("STT 语音识别 (Whisper)", "STT speech recognition (Whisper)"),
			["voice.sttHint"] = ("录音在本地完成后上传至 OpenAI 兼容接口。", "Audio is recorded locally and sent to an OpenAI-compatible endpoint."),
			["voice.sttBaseUrl"] = ("Whisper API 地址", "Whisper API URL"),
			["voice.sttApiKey"] = ("Whisper API Key", "Whisper API Key"),
			["proactive.title"] = ("主动交互与日常关怀", "Proactive Interaction & Daily Care"),
			["proactive.subtitle"] = ("配置挂机互动、日常问候与可恢复提醒", "Configure idle care, daily greetings and recoverable reminders"),
			["proactive.idle"] = ("挂机主动关怀", "Idle care"),
			["proactive.idleEnabled"] = ("无操作挂机互动", "Interact when idle"),
			["proactive.idleDesc"] = ("长时间无操作时主动向主人表达关怀。", "Offer care after a period without input."),
			["proactive.interval"] = ("挂机触发间隔", "Idle trigger interval"),
			["proactive.daily"] = ("日常时钟问候", "Daily greetings"),
			["proactive.dailyEnabled"] = ("定点生活问候", "Scheduled greetings"),
			["proactive.dailyDesc"] = ("在早晨、午餐和深夜主动问候与提醒休息。", "Greet you and remind you to rest during the day."),
			["proactive.reminders"] = ("定时提醒任务", "Scheduled reminders"),
			["proactive.add"] = ("添加提醒", "Add reminder"),
			["proactive.empty"] = ("暂无排队中的提醒事项。", "No reminders are queued."),
			["memory.title"] = ("长期记忆库管理", "Long-term Memory"),
			["memory.subtitle"] = ("管理 Nori 记录的偏好、事实与约定事项", "Manage preferences, facts and agreements remembered by Nori"),
			["memory.embedding"] = ("向量嵌入与语义检索", "Embedding & semantic search"),
			["memory.model"] = ("Embedding 模型", "Embedding model"),
			["memory.baseUrl"] = ("API 地址", "API URL"),
			["memory.apiKey"] = ("API Key", "API Key"),
			["memory.dimensions"] = ("向量维数", "Dimensions"),
			["memory.reembed"] = ("重新计算记忆向量", "Rebuild vectors"),
			["memory.add"] = ("添加长期记忆", "Add memory"),
			["memory.save"] = ("保存记忆", "Save memory"),
			["memory.list"] = ("记忆列表", "Memory list"),
			["memory.search"] = ("搜索记忆关键词…", "Search memories…"),
			["memory.clear"] = ("清空所有记忆", "Clear all memories"),
			["memory.empty"] = ("暂无已保存的长期记忆。", "No long-term memories saved."),
			["skills.title"] = ("技能工坊", "Skills Workshop"),
			["skills.subtitle"] = ("管理已安装技能、市场预设与自定义技能", "Manage installed, marketplace and custom skills"),
			["skills.installed"] = ("已安装", "Installed"),
			["skills.market"] = ("技能市场", "Marketplace"),
			["skills.url"] = ("从 URL 安装", "Install from URL"),
			["skills.new"] = ("新建技能", "New skill"),
			["skills.empty"] = ("未找到匹配的技能。", "No matching skills found."),
			["skills.toggle"] = ("启用", "Enabled"),
			["skills.detail"] = ("查看指令", "View instructions"),
			["skills.edit"] = ("编辑", "Edit"),
			["skills.uninstall"] = ("卸载", "Uninstall"),
			["skills.uninstallConfirm"] = ("确定卸载“{0}”吗？", "Uninstall “{0}”?"),
			["mcp.title"] = ("MCP 与工具", "MCP & Tools"),
			["mcp.subtitle"] = ("管理后端 MCP 服务与内置工具，工具调用始终由 C# 执行。", "Manage MCP servers and built-in tools. Calls always execute in C#."),
			["mcp.servers"] = ("MCP 服务器", "MCP servers"),
			["mcp.tools"] = ("内置工具", "Built-in tools"),
			["mcp.add"] = ("添加服务器", "Add server"),
			["mcp.import"] = ("导入 URL", "Import URL"),
			["mcp.empty"] = ("尚未配置 MCP 服务器。", "No MCP servers configured."),
			["mcp.connect"] = ("连接", "Connect"),
			["mcp.disconnect"] = ("断开", "Disconnect"),
			["mcp.delete"] = ("删除", "Delete"),
			["mcp.test"] = ("测试连接", "Test connection"),
			["mcp.execute"] = ("执行", "Execute"),
			["general.title"] = ("系统与常规设置", "General & System Settings"),
			["general.subtitle"] = ("管理语言、启动偏好与客户端基础信息", "Manage language, startup preferences and client information"),
			["general.language"] = ("显示语言", "Display language"),
			["general.chinese"] = ("简体中文", "Simplified Chinese"),
			["general.english"] = ("English (US)", "English (US)"),
			["general.startup"] = ("启动与运行行为", "Startup & runtime behavior"),
			["general.autoSummon"] = ("启动时自动唤出桌宠", "Summon the pet on startup"),
			["general.autoSummonDesc"] = ("初始化完成后自动在桌面上显示 Nori。", "Show Nori automatically after initialization."),
			["general.about"] = ("应用与环境信息", "Application & environment"),
			["general.version"] = ("客户端版本", "Client version"),
			["general.license"] = ("开源协议", "License"),
			["general.renderer"] = ("渲染引擎", "Renderer"),
			["debug.title"] = ("调试与诊断", "Debug & Diagnostics"),
			["debug.subtitle"] = ("查看运行状态、日志并验证异常兜底链路", "Inspect runtime state, logs and failure handling"),
			["debug.warning"] = ("本页仅供调试使用，危险操作可能弹出崩溃窗甚至退出应用。", "For debugging only. Dangerous actions can show crash dialogs or exit the app."),
			["debug.diagnostic"] = ("运行诊断", "Runtime diagnostics"),
			["debug.logs"] = ("运行日志", "Runtime logs"),
			["debug.refresh"] = ("刷新", "Refresh"),
			["debug.clear"] = ("清空", "Clear"),
			["debug.copy"] = ("复制", "Copy"),
			["debug.openFolder"] = ("打开日志文件夹", "Open log folder"),
			["debug.gc"] = ("触发垃圾回收", "Collect garbage"),
			["debug.testLog"] = ("写入测试日志", "Write test log"),
			["debug.danger"] = ("危险操作", "Dangerous actions"),
			["debug.features"] = ("功能测试", "Feature tests"),
			["debug.noLogs"] = ("暂无匹配的日志", "No matching logs"),
			["debug.clearConfirm"] = ("确定清空内存中的日志缓冲吗？磁盘日志不会删除。", "Clear the in-memory log buffer? Disk logs will not be deleted."),
			["debug.crashUi"] = ("UI 线程崩溃测试", "UI thread crash test"),
			["debug.crashBackground"] = ("后台线程崩溃测试", "Background thread crash test"),
			["debug.crashTask"] = ("未观察任务异常", "Unobserved task exception"),
			["debug.crashExitConfirm"] = ("该探针会导致进程退出，确定继续吗？", "This probe will terminate the process. Continue?"),
			["debug.crashConfirm"] = ("该探针会触发异常处理流程，确定继续吗？", "This probe triggers the exception handling flow. Continue?"),
			["ai.baseUrlError"] = ("请先填写 API 地址", "Enter an API URL first"),
			["voice.gptUrl"] = ("GPT-SoVITS API 地址", "GPT-SoVITS API URL"),
			["proactive.fiveMinutes"] = ("5 分钟", "5 minutes"),
			["proactive.fifteenMinutes"] = ("15 分钟", "15 minutes"),
			["proactive.thirtyMinutes"] = ("30 分钟", "30 minutes"),
			["proactive.oneHour"] = ("60 分钟", "60 minutes"),
			["proactive.fiveLater"] = ("5 分钟后", "In 5 minutes"),
			["proactive.fifteenLater"] = ("15 分钟后", "In 15 minutes"),
			["proactive.thirtyLater"] = ("30 分钟后", "In 30 minutes"),
			["proactive.oneHourLater"] = ("1 小时后", "In 1 hour"),
			["proactive.twoHoursLater"] = ("2 小时后", "In 2 hours"),
			["proactive.cancelConfirm"] = ("确定取消“{0}”吗？", "Cancel “{0}”?"),
			["memory.content"] = ("内容", "Content"),
			["memory.contentHint"] = ("输入需要让 Nori 记住的内容…", "Enter something Nori should remember…"),
			["memory.tags"] = ("标签", "Tags"),
			["memory.tagsHint"] = ("偏好, 饮食", "preferences, food"),
			["memory.importance"] = ("重要度", "Importance"),
			["memory.delete"] = ("删除记忆", "Delete memory"),
			["memory.deleteConfirm"] = ("确定删除这条记忆吗？", "Delete this memory?"),
			["memory.clearConfirm"] = ("确定清空全部长期记忆吗？此操作不可恢复。", "Clear all long-term memories? This cannot be undone."),
			["skills.search"] = ("搜索技能名称、描述或标签…", "Search skill name, description or tags…"),
			["skills.all"] = ("全部技能", "All skills"),
			["skills.productivity"] = ("生产力与效率", "Productivity"),
			["skills.coding"] = ("编程与架构", "Coding & architecture"),
			["skills.life"] = ("生活与学习", "Life & learning"),
			["skills.roleplay"] = ("情感与角色", "Emotion & roleplay"),
			["skills.entertainment"] = ("游戏与娱乐", "Games & entertainment"),
			["skills.install"] = ("一键安装", "Install"),
			["skills.remoteUrl"] = ("远程文件 URL", "Remote file URL"),
			["skills.formName"] = ("技能名称", "Skill name"),
			["skills.formDescription"] = ("技能简介", "Description"),
			["skills.formAuthor"] = ("作者", "Author"),
			["skills.formVersion"] = ("版本", "Version"),
			["skills.formCategory"] = ("分类", "Category"),
			["skills.formTags"] = ("标签 (逗号分隔)", "Tags (comma separated)"),
			["skills.formTools"] = ("推荐工具 (逗号分隔)", "Recommended tools (comma separated)"),
			["skills.formInstructions"] = ("技能指令", "Instructions"),
			["mcp.search"] = ("搜索服务器或工具…", "Search servers or tools…"),
			["mcp.testTool"] = ("测试工具", "Test tool"),
			["mcp.enabled"] = ("启用", "Enabled"),
			["mcp.disabled"] = ("停用", "Disabled"),
			["mcp.noTools"] = ("未找到匹配的工具。", "No matching tools found."),
			["mcp.noServers"] = ("尚未配置 MCP 服务器。", "No MCP servers configured."),
			["mcp.formName"] = ("名称", "Name"),
			["mcp.formTransport"] = ("传输协议 (stdio / sse)", "Transport (stdio / sse)"),
			["mcp.formCommand"] = ("命令", "Command"),
			["mcp.formArgs"] = ("参数 (空格分隔)", "Arguments (space separated)"),
			["mcp.formEnv"] = ("环境变量 (每行 KEY=VALUE)", "Environment (one KEY=VALUE per line)"),
			["mcp.formUrl"] = ("SSE 地址", "SSE URL"),
			["mcp.importUrl"] = ("配置 URL", "Configuration URL"),
			["mcp.testFailed"] = ("连接测试失败", "Connection test failed"),
			["mcp.deleteConfirm"] = ("确定删除“{0}”的配置吗？", "Delete the configuration for “{0}”?"),
			["mcp.toolCount"] = ("工具", "Tools"),
			["mcp.formId"] = ("ID", "ID"),
			["mcp.newName"] = ("新 MCP 服务", "New MCP server"),
			["mcp.notReady"] = ("MCP 服务未就绪，仍然保存吗？", "MCP is not ready. Save anyway?"),
			["mcp.testJson"] = ("JSON 参数", "JSON arguments"),
			["mcp.emptyResult"] = ("(空结果)", "(empty result)"),
		};

	private static bool _english;

	/// <summary>资源切换通知。</summary>
	public static event Action? Changed;

	/// <summary>当前是否为英文资源。</summary>
	public static bool IsEnglish => _english;

	/// <summary>根据持久化语言切换显示资源。</summary>
	public static void SetLanguage(string? language)
	{
		bool english = string.Equals(language, "en-US", StringComparison.OrdinalIgnoreCase);
		if (_english == english) return;
		_english = english;
		Changed?.Invoke();
	}

	/// <summary>读取资源字典中的文本。</summary>
	public static string Text(string key)
	{
		if (!Resources.TryGetValue(key, out (string Zh, string En) value)) return key;
		return _english ? value.En : value.Zh;
	}

	/// <summary>用于 Fluent 导航图标的主题色。</summary>
	public static IBrush AccentBrush { get; } = new SolidColorBrush(Color.Parse("#7DE3FF"));
}
