<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Nori.PluginRuntime</RootNamespace>
		<AssemblyName>Nori.PluginRuntime</AssemblyName>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Nori.PluginRuntime.Tests" />
		<InternalsVisibleTo Include="Nori.Desktop" />
		<InternalsVisibleTo Include="Nori.Desktop.Tests" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.1.1" />
		<PackageReference Include="Avalonia.Controls.WebView" Version="12.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../Nori.Core/Nori.Core.csproj" />
	</ItemGroup>
</Project>
