<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Nori.Plugin.Games.Abstractions</RootNamespace>
		<AssemblyName>Nori.Plugin.Games.Abstractions</AssemblyName>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="../Nori.Plugin.Abstractions/Nori.Plugin.Abstractions.csproj" />
	</ItemGroup>
</Project>
