<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Nori.Plugin.Runtime</RootNamespace>
		<AssemblyName>Nori.Plugin.Runtime</AssemblyName>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="../Nori.Plugin.Abstractions/Nori.Plugin.Abstractions.csproj" />
		<ProjectReference Include="../Nori.Plugin.Games.Abstractions/Nori.Plugin.Games.Abstractions.csproj" />
		<ProjectReference Include="../Nori.Plugin.Arcade.Abstractions/Nori.Plugin.Arcade.Abstractions.csproj" />
		<ProjectReference Include="../Nori.Plugin.Harness.Abstractions/Nori.Plugin.Harness.Abstractions.csproj" />
		<ProjectReference Include="../Nori.Core/Nori.Core.csproj" />
	</ItemGroup>
</Project>
