# 网关配置
gateway:
    # 监听端口
    port: 8084
    # 数据路径
    data-path: "data"
    # 临时路径
    temp-path: "tmp"

# 日志配置
logger:
    # 日志输出方式 (both, file, stdout)
    # both: 输出到文件和控制台
    # file: 输出到文件
    # stdout: 输出到控制台
    output: "both"
    # 日志级别 (debug, info, warn, error)
    level: "info"
    # 系统日志文件路径
    log-path: "logs/api-gateway.log"
    # 请求日志文件路径
    request-log-path: "logs/request.log"
    # 日志文件最大大小(MB)
    max-size: 100
    # 日志文件最大备份数量
    max-backups: 10
    # 日志文件最大年龄(天)
    max-age: 30
    # 是否压缩日志文件
    compress: true
